### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by a-pandey**
script file is not recognised with ' / ' in start of the path.

### CODE REVIEW

**Comment by a-pandey** [comment]
Hey! I've signed for CLA.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by PaulKinlan** [comment]
It should be recognised.

**Comment by PaulKinlan** [comment]
I am not sure how you are running this, but it works fine when run from localhost.

Please re-open if you are still having issues.

**Comment by a-pandey** [comment]
Yes. I was running index.html directly in browser.

**Pull request closed without merging**
